name: docs
on:
  push: { branches: [main] }
  pull_request:
permissions: { contents: read, pages: write, id-token: write }
jobs:
  docs:
    uses: Zebradil/docs-kit/.github/workflows/docs.yml@83e7c736c91fe328c7b23bf7eca2e0a4a6fb5141 # v0.2.0
